import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import path from 'path'
import Layout from '../../components/Layout'
import { getAllLessonPaths } from '../../lib/getAllLessonsPaths'
import { LESSONS_PATH } from '../../lib/CONSTANTS'
export default function Index({ lessons }) {
  return (
    <Layout>
      testies
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {lessons.map(lesson => (
          <li key={lesson.slug}>
            <Link as={`/lesson/${lesson.slug}`} href={`/lesson/[slug]`}>
              <a>{lesson.metaData.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export async function getStaticProps() {
  const lessons = await getAllLessonPaths().map(({ params: { slug } }) => {
    const metaPath = path.join(LESSONS_PATH, slug, 'meta.json')
    const metaData = JSON.parse(fs.readFileSync(metaPath))
    console.log('data', metaData)
    return {
      slug,
      metaData
    }
  })

  console.log(lessons)
  //   const lessons = postFilePaths.map(filePath => {
  //     const source = fs.readFileSync(path.join(POSTS_PATH, filePath))
  //     const { content, data } = matter(source)

  //     return {
  //       testies: 'test'
  //     }
  //   })

  return { props: { lessons } }
}
